[package]
name = "evenframe"
version = "0.1.0"
edition = "2021"


[dependencies]
handlers = { path = "../handlers" }
helpers = { path = "../helpers" }
surrealdb = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
dotenv = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde.workspace = true
rand = { workspace = true }
rand_distr = { workspace = true }
heck = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
derive_more = { workspace = true }
petgraph = { workspace = true }
toml = { workspace = true }
