[package]
name = "evenframe"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib/mod.rs"


[dependencies]
surrealdb = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
dotenv = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde.workspace = true
rand = { workspace = true }
rand_distr = { workspace = true }
heck = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
derive_more = { workspace = true }
petgraph = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
bon = { workspace = true }
convert_case = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }
ordered-float = { version = "5.0.0", features = ["serde"] }
try_from_expr = { path = "../try_from_expr" }
serde-value = { workspace = true }
thiserror = { workspace = true }
derive-syn-parse = "0.2.0"
